import Link from "next/link";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Home() {
  console.log(process.env.NODE_ENV)
  return (
    <div>
      <h1 className="text-3xl font-bold">Welcome to Dashboard</h1>
      <p className="text-gray-600">Manage your users and profile here.</p>
      <div className="flex gap-4 mt-4">
        <Link href="/users" className="btn btn-primary">View Users</Link>
        <Link href="/profile" className="btn btn-secondary">Go to Profile</Link>
      </div>
    </div>
  );
}
